---
- hosts: client
  become: True
  tasks:

    - name: Install docker for client
      apt:
        name: docker-ce
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: start the container
      docker_container:
        name: image
        image: "thai2305/nginx:$BUILD_NUMBER"
        state: started
        published_ports:
          - 0.0.0.0:8080:80