---
- hosts: client
  become: True
  tasks:
    
    - name: Install docker
      apt:
        name: docker-ce
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: start the container
      docker_container:
        name: image
        image: "thai2305/nginx:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080